# -*- coding: utf-8 -*-
"""OpenAIPrompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCSnyIQ-zie-jev2WFlieihDz8Ngrb7o
"""

import os
import openai
import tiktoken
from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv()) # read local .env file

openai.api_key  = os.environ['OPENAI_API_KEY']